### ISSUE TITLE
这些exe打不开，main.py代码似乎是作者恶搞

### ISSUE THREAD

**Issue by How-Delicious-Shit-is** [chenhen666/henVIP#3]
点击henVIP-desktop.exe出现这样的情况，favicon.ico这个文件在哪里，需要放到哪里
|Traceback (most recent call last):
  File "VIP.py", line 100, in <module>
  File "VIP.py", line 18, in __init__
  File "tkinter\__init__.py", line 2136, in wm_iconbitmap
_tkinter.TclError: bitmap "favicon.ico" not defined

main.py
#哥们你觉得我会给你看源代码吗？
===========================
while True:
    print("哥们你觉得我会给你看源代码吗？")

**Comment by zion325** [comment]
> 点击henVIP-desktop.exe出现这样的情况，favicon.ico这个文件在哪里，需要放到哪里 |Traceback (most recent call last): File "VIP.py", line 100, in File "VIP.py", line 18, in **init** File "tkinter__init__.py", line 2136, in wm_iconbitmap _tkinter.TclError: bitmap "favicon.ico" not defined
> 
> # main.py
> #哥们你觉得我会给你看源代码吗？
> while True: print("哥们你觉得我会给你看源代码吗？")

下载‘favicon.ico’这个文件，放同一个目录下, 就可以运行了。不过没必要下载，直接粘贴 ‘解析接口+视频连接’ 到浏览器就行，能不能解析看运气。。。。例如 https://jx.m3u8.tv/jiexi/?url=你的视频地址

**Comment by so-what-should-i-do** [comment]
其实网上有许多视频解析的接口 他这个程序本质也是找个解析网站然后用 这种封装的极可能已经失效了

**Comment by ghost** [comment]
就调个接口的事，搞的神神秘秘的，不会逆向不会做爬虫就别做
